apiVersion: v1
kind: Service
metadata:
  name: ml-grpc-service
spec:
  type: NodePort
  selector:
    app: ml-grpc
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30051