apiVersion: v1
kind: Service
metadata:
  name: ml-flask-service
spec:
  type: NodePort
  selector:
    app: ml-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005